[build]
  base = "client"
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API proxy for production
[[redirects]]
  from = "/api/*"
  to = "https://meymad-pool.onrender.com/:splat"
  status = 200
  force = true

# Socket.IO proxy
[[redirects]]
  from = "/socket.io/*"
  to = "https://meymad-pool.onrender.com/socket.io/:splat"
  status = 200
  force = true
