[build]
  base = "client"
  command = "npm install && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API proxy for production
[[redirects]]
  from = "/auth/*"
  to = "https://meymad-pool.onrender.com/auth/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/users/*"
  to = "https://meymad-pool.onrender.com/users/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/reservations/*"
  to = "https://meymad-pool.onrender.com/reservations/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/comments/*"
  to = "https://meymad-pool.onrender.com/comments/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/messages/*"
  to = "https://meymad-pool.onrender.com/messages/:splat"
  status = 200
  force = true

# Socket.IO proxy
[[redirects]]
  from = "/socket.io/*"
  to = "https://meymad-pool.onrender.com/socket.io/:splat"
  status = 200
  force = true
