export const infoStyles = {
  root: {
    minHeight: "100vh",
    bgcolor: "linear-gradient(135deg, #b2ebf2 0%, #e0f7fa 50%, #80deea 100%)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    p: 2,
  },
  container: {
    width: "100%",
    maxWidth: 900,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: { xs: 2, sm: 4 },
    bgcolor: "transparent",
    px: { xs: 2, sm: 4 },
  },
  title: {
    letterSpacing: 1,
    mb: 1,
    textAlign: "center",
    textShadow: "0 2px 8px #b2ebf2",
    color: "#0097a7",
    fontWeight: 700,
    fontSize: { xs: '1.8rem', sm: '2.125rem' },
  },
  rowArea: {
    width: "100%",
    display: "flex",
    flexDirection: { xs: "column", md: "row" },
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    bgcolor: "transparent",
  },
  details: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    width: "100%",
    maxWidth: 500,
    bgcolor: "transparent",
    position: "relative",
    minHeight: { xs: 300, sm: 350 },
  },
  editButtons: {
    position: "absolute",
    bottom: 0,
    right: 0,
    display: "flex",
    gap: 1,
    mt: 2,
  },
  profile: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    minWidth: 220,
    mb: { xs: 4, md: 0 },
    mt: { xs: 0, md: -40 },
  },
  avatar: {
    width: { xs: 100, sm: 120 },
    height: { xs: 100, sm: 120 },
    bgcolor: "#4dd0e1",
    color: "#fff",
    fontSize: { xs: 50, sm: 60 },
    fontWeight: "bold",
    boxShadow: 4,
    border: "4px solid #fff",
    mb: 2,
  },
  profileName: {
    letterSpacing: 1,
    mt: 1,
    textShadow: "0 2px 8px #b2ebf2",
    color: "#0097a7",
    fontWeight: 700,
    fontSize: { xs: '1.2rem', sm: '1.5rem' },
  },
  editBtn: {
    borderRadius: 3,
    fontWeight: 700,
    mx: 0.5,
    color: "#00bcd4",
    borderColor: "#00bcd4",
    "&:hover": { bgcolor: "#e0f7fa" }
  },
  saveBtn: {
    borderRadius: 3,
    fontWeight: 700,
    mx: 0.5,
    bgcolor: "#00bcd4",
    color: "#fff",
    "&:hover": { bgcolor: "#0097a7" }
  },
  cancelBtn: {
    borderRadius: 3,
    fontWeight: 700,
    mx: 0.5,
  }
};